config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cities#index'
  get 'cities', to: 'cities#index'
  get 'cities/search', to: 'cities#search'
  get 'cities/:name', to: 'cities#show', as: 'city'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City
    attr_accessor :name
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

    before_action :dad_joke

    def search
        redirect_to city_path(name: params[:name])
    end

    def show
        require 'net/http'
        require 'json'

        @city = params[:name.to_s]
        @color = ""

        # Current Weather
        @url = "https://api.openweathermap.org/data/2.5/weather?q=#{@city}&appid=b3de74108cc43d86835f3312a5074990"
        @uri = URI(@url)
        @response = Net::HTTP.get(@uri)
        @output = JSON.parse(@response)

        # Current Weather Outputs
        
        @temp = nil

        if @output["main"] && @output["main"]["temp"]
            @temp = @output["main"]["temp"]
    
            # Forecast Weather
            @forecast_url = "https://api.openweathermap.org/data/2.5/forecast?q=#{@city}&appid=b3de74108cc43d86835f3312a5074990"
            @forecast_uri = URI(@forecast_url)
            @forecast_response = Net::HTTP.get(@forecast_uri)
            @forecast_output = JSON.parse(@forecast_response)

            # Forecast Weather Outputs
            @total = @forecast_output["list"]

            add

        end

        @search = Search.order(id: :desc).limit(3)
    end

    def dad_joke
        # Random Dad Joke Generator
        @dad_joke_url = "https://us-central1-dadsofunny.cloudfunctions.net/DadJokes/random/jokes"
        @dad_joke_uri = URI(@dad_joke_url)
        @dad_joke_response = Net::HTTP.get(@dad_joke_uri)
        @dad_joke_output = JSON.parse(@dad_joke_response)
    end

    def add
        Search.create(search: params[:name.to_s])
    end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController

    before_action :show

    def index
        @temp
    end

    def show
        require 'net/http'
        require 'json'

        @city = params[:city.to_s]

        @url = "https://api.openweathermap.org/data/2.5/weather?q=#{@city}&appid=b3de74108cc43d86835f3312a5074990"
        @uri = URI(@url)
        @response = Net::HTTP.get(@uri)
        @output = JSON.parse(@response)
        @temp = @output[:main.to_s][:temp.to_s]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.erb
<section class="mainPageBackground">
    <section class="dadJokeSection">
            <h2 class="mainHeadingOne">The A Team</h2>
            <h1 class="mainHeadingTwo">Weather Forecaster</h1>
    </section>
    <section class="mainPageContentBox">
        <section class="mainPageContentBoxElements">
            <%= form_with url: cities_search_path, method: :get, local: true do |form| %>
                <section class="formCitySubmit">
                    <%= form.label :City, class: "formLabel" %>
                    <%= form.text_field :name, class: "formInput" %>
                    <%= form.submit "Check Weather", class: "formSubmitButton" %>
                </section>
            <% end %>
        </section>
    </section>
    <section class="dadJokeSection">
        <p class="dadJokeSetup"><%= @dad_joke_output["setup"] %></p>
        <p class="dadJokePunchline"><%= @dad_joke_output["punchline"] %></p>
    </section>
</section>

app/views/cities/show.html.erb
<% if @temp.nil? %>
   <section>
        <h1>City Not Found</h1>
        <%= link_to "Back", "/" %>
   </section>
<% else %>

<section class="currentWeatherSection">
    <section class="currentWeatherContainer">

    <div style="background-color:<%= @color %>">

        <div class="currentLocationMainElements">
            <img class="currentLocationWeatherIcon" src="http://openweathermap.org/img/w/<%= @output["weather"][0]["icon"] %>.png">
            <h1 class="currentLocationShowTitle"><%= @city %> Weather</h1>
            <div class="currentLocationTempAndDescriptionSection">
                <h2 class="currentLocationShowTemp">Current Temp: <%= (@output["main"]["temp"].to_f - 273.15).round(2) %>°C</h2>
                <h2 class="currentLocationShowDescription">Description: <%= @output["weather"][0]["description"] %></h2>
            </div>
        </div>
        <section class="currentWeatherMainOutput">
            <div class="currentWeatherOutputModule">
                <h2>Feels Like: <%= (@output["main"]["feels_like"].to_f - 273.15).round(2) %>°C</h2>
            </div>
            <div class="currentWeatherOutputModule"v>
                <h2>Min Temp: <%= (@output["main"]["temp_min"].to_f - 273.15).round(2) %>°C</h2>
            </div>
            <div class="currentWeatherOutputModule">
                <h2>Max Temp: <%= (@output["main"]["temp_max"].to_f - 273.15).round(2) %>°C</h2>
            </div>
            <div class="currentWeatherOutputModule">
                <h2>Humidity: <%= @output["main"]["humidity"] %>%</h2>
            </div>
        <section>
    </section>
</section>

<section class="forecastTitleSection">
    <h2 class="fiveDayForecastTitleText"><%= @city.capitalize %> 5 Day Forecast</h2>
</section>

<section class="forecastSection">
    <section class="forecastSectionMain">
        <div class="forecastOutputContainers">
            <div class="forecastOutputContainersMainInfo">
                <p><%= @total[9]["dt_txt"] %></p>
                <div><img src="http://openweathermap.org/img/w/<%= @total[9]["weather"][0]["icon"] %>.png"></div>
                <p><%= @total[9]["weather"][0]["description"] %></p>
            </div>
            <p>Temperature: <%= (@total[9]["main"]["temp"].to_f - 273.15).round(2) %>°C</p>
            <p>Min Temp: <%= (@total[9]["main"]["temp_min"].to_f - 273.15).round(2) %>°C</p>
            <p>Max Temp: <%= (@total[9]["main"]["temp_max"].to_f - 273.15).round(2) %>°C</p>
            <p>Humidity: <%= @total[9]["main"]["humidity"] %>%</p>
        </div>


        <div class="forecastOutputContainers">
            <div class="forecastOutputContainersMainInfo">
                <p><%= @total[15]["dt_txt"] %></p>
                <div><img src="http://openweathermap.org/img/w/<%= @total[9]["weather"][0]["icon"] %>.png"></div>
                <p><%= @total[15]["weather"][0]["description"] %></p>
            </div>
            <p>Temperature: <%= (@total[15]["main"]["temp"].to_f - 273.15).round(2) %>°C</p>
            <p>Min Temp: <%= (@total[15]["main"]["temp_min"].to_f - 273.15).round(2) %>°C</p>
            <p>Max Temp: <%= (@total[15]["main"]["temp_max"].to_f - 273.15).round(2) %>°C</p>
            <p>Humidity: <%= @total[15]["main"]["humidity"] %>%</p>
        </div>


        <div class="forecastOutputContainers">
            <div class="forecastOutputContainersMainInfo">
                <p><%= @total[25]["dt_txt"] %></p>
                <div><img src="http://openweathermap.org/img/w/<%= @total[9]["weather"][0]["icon"] %>.png"></div>
                <p><%= @total[25]["weather"][0]["description"] %></p>
            </div>
            <p>Temperature: <%= (@total[25]["main"]["temp"].to_f - 273.15).round(2) %>°C</p>
            <p>Min Temp: <%= (@total[25]["main"]["temp_min"].to_f - 273.15).round(2) %>°C</p>
            <p>Max Temp: <%= (@total[25]["main"]["temp_max"].to_f - 273.15).round(2) %>°C</p>
            <p>Humidity: <%= @total[25]["main"]["humidity"] %>%</p>
        </div>


        <div class="forecastOutputContainers">
            <div class="forecastOutputContainersMainInfo">
                <p><%= @total[33]["dt_txt"] %></p>
                <div><img src="http://openweathermap.org/img/w/<%= @total[9]["weather"][0]["icon"] %>.png"></div>
                <p><%= @total[33]["weather"][0]["description"] %></p>
            </div>
            <p>Temperature: <%= (@total[33]["main"]["temp"].to_f - 273.15).round(2) %>°C</p>
            <p>Min Temperature: <%= (@total[33]["main"]["temp_min"].to_f - 273.15).round(2) %>°C</p>
            <p>Max Temperature: <%= (@total[33]["main"]["temp_max"].to_f - 273.15).round(2) %>°C</p>
            <p>Humidity: <%= @total[33]["main"]["humidity"] %>%</p>
        </div>


        <div class="forecastOutputContainers">
            <div class="forecastOutputContainersMainInfo">
                <p><%= @total[39]["dt_txt"] %></p>
                <div><img src="http://openweathermap.org/img/w/<%= @total[9]["weather"][0]["icon"] %>.png"></div>
                <p><%= @total[39]["weather"][0]["description"] %></p>
            </div>
            <p>Temperature: <%= (@total[39]["main"]["temp"].to_f - 273.15).round(2) %>°C</p>
            <p>Min Temp: <%= (@total[39]["main"]["temp_min"].to_f - 273.15).round(2) %>°C</p>
            <p>Max Temp: <%= (@total[39]["main"]["temp_max"].to_f - 273.15).round(2) %>°C</p>
            <p>Humidity: <%= @total[39]["main"]["humidity"] %>%</p>
        </div>
    </section>
</section>

<section class="previousSearchesTitleSection">
    <h2 class="previousSearchesTitleText"> Recent Searches </h2>
</section>

<section class="previousSearchesSection">
    <div class="previousSearches">
        <% @search.each do | search | %>
            <a href="https://a-team-weather-app.herokuapp.com/cities/<%= search[:search] %>" class="previousSearch"><%= search[:search] %></a>
        <% end %>
    </div>
</section>

<section class="backButtonSection">
    <div class="backButton"><%= link_to "Back", "/" %></div>
<section>

</section>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ABuiDevsTheWeather</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @weather.city %>
</p>

<%= link_to 'Edit', edit_weather_path(@weather) %> |
<%= link_to 'Back', weathers_path %>